#!/usr/bin/env bash

function usage {
    cat <<EOF
Usage: $0 [file or folder]

Lint shell script files from a single file or from folder
EOF
}

[ -z "$1" ] && (usage 1>&2; exit 1)

target="$1"

if [ -f "$target" ]
then
    linguist "$target" | grep "language: *Shell" | shellcheck "$target"
elif [ -d "$target" ]
then
    find "$target" -type f -print0 |
        while IFS= read -r -d $'\0' shell_script
        do
            linguist "$shell_script" |
                grep -q 'language: *Shell' && echo -n "$shell_script" && shellcheck "$shell_script"
            [ $? -eq 0 ] && echo -e " \e[32mOK\e[0m"
        done
else
    echo "No files to shlint from $target" 1>&2
    exit 1
fi

